# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo "tasks - init"
    before: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
    command: |
      echo $VOLT_API_P12_FILE | base64 -d > ~/.api-creds.p12
      export VOLT_API_P12_FILE=~/.api-creds.p12
      if [ ! -z "$VOLT_API_CA_CERT" ]; then
        echo $VOLT_API_CA_CERT | base64 -d > ~/.public_server_ca.crt
        export VOLT_API_CA_CERT=~/.public_server_ca.crt
      fi
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
